# Generated by Django 5.0.6 on 2024-06-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategory',
            old_name='categoryName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='tasks',
        ),
    ]
