# Generated by Django 5.0.6 on 2024-06-08 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_categorymodel_delete_taskcategory'),
        ('task', '0005_remove_taskmodel_is_complited_taskmodel_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='task.taskmodel'),
            preserve_default=False,
        ),
    ]
