# Generated by Django 5.0.6 on 2024-06-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='taskAssignDate',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='taskDescription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='taskTitle',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
