# Generated by Django 5.0.6 on 2024-06-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_taskassigndate_taskmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='created_at',
            new_name='task_assign_date',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='updated_at',
        ),
    ]
