# Generated by Django 5.0.6 on 2024-06-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_created_at_taskmodel_task_assign_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='is_complited',
            field=models.BigIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
