# Generated by Django 5.0.6 on 2024-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_taskmodel_is_completed_taskmodel_is_complited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='is_complited',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
